sudo: required
services:
  - docker


before_install:
  - docker build -t nestor94/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true nestor94/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-test-react"
  env: "DockerTestReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-633334446742"
  bucket_path: "docker-test-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"